project:
  type: website
  output-dir: docs

website:
  title: "Kristina Riemer"
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - teaching.qmd
      - community.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: false



